### ISSUE TITLE
color normalization

### ISSUE THREAD

**Issue by yasohasakii** [vbookshelf/Breast-Cancer-Analyzer#1]
Hi , is there a necessarity for color-normalizing those H&E stained histopathology images as a preprocess part before training a deep learning network.

**Comment by vbookshelf** [comment]
Hi Jum,

I managed to get good results without using any color normalizing techniques. But I did normalize the images so that all pixels hand a value between 0 and 1. The code for this is inside the data generator:

datagen = ImageDataGenerator(rescale=1.0/255)

This is a link to the Kaggle Histopathologic Cancer Detection competition where you will be able to find more notebooks that show how others approached this problem:
https://www.kaggle.com/c/histopathologic-cancer-detection/overview

**Comment by yasohasakii** [comment]
Ok, It seems color-normalization is not necessary for kaggle histopathologic dataset, that helps me a lot, thx.
